name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install minimal deps
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Lint
        run: |
          flake8 src app || true
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
      - name: Import smoke test
        run: |
          python - << 'PY'
          try:
              import src.generate as g
              print('IMPORT_OK', bool(getattr(g, 'get_pipeline', None)))
          except Exception as e:
              print('IMPORT_FAIL', e)
          PY
